---
settings:
  checkpoint: "tshufflenetv2k30"
  decoder: ["trackingpose:0"]
  long_edge: 321
  show: True
  source: "../../skating.mp4"
  video_output: "outputs/skating.mp4"
  json_output: "outputs/skating.json"
  disable_cuda: False